DNA_ReverseComplement = {
    "A": "T",
    "T": "A",
    "G": "C",
    "C": "G",
}  # fastest way to swap letters


def dna_reverse_complement(sequence):
    """Swapping adenine with thymine and quanine with cytosine. Reversing newly generated string."""
    return "".join([DNA_ReverseComplement[nucleotide] for nucleotide in sequence])[
        ::-1
    ]  # reverse


string = "TGCAGCGAGTTGGACACATGGGATCGCCAAGAGGACACGGCTTGCCCGCTCCGCTACTACTGTTACGTCTCGTGGCAGCCCAAAGCAGGACTAACAGTCGCCTAGAACGGTGCGAGTGTCCACTCCCTGATAGACGTGGATCACGCTGCGGCTCGACCCTGACCAGCTAAAGAACTTGGGCGAGGATTTTCCTTACCTCCGCCTGATGTTTGGCCCCAGATTAAACGCTCTAGCAACCGTCTCTCATCGGTCCTGATGTGATACTCTGGTACGTCGCAGTGCTTACTGAGATTGCTCGTTCAGGTGACCTTGAAGCATCCCGTGGGCGTTTGAAGGGGGGCATGTTCTGACGTTCTTCTAGGCTATGTGCACAAGCCCCTCATGGGAACCTAAAATAGTCGGTTTGGTTTAAAAATATCATAAGATGCATCACCCCAAAGGAATCTTCTCGGTCGCTAGCTAAGTTACCTTATTCATTACTTGACTCGCCGGATATCCAAGCTGCTCGTTTCTATTACTGAATGGGCGGCGCCCATGAATGATCTTTGGGAGTGCACCACGGGAAAATTATATCATTGAATAAGACTAGAAATTACACGGCGCATCCATCGGGTAAACTGGATTCCACCGTCTGCGAAGGAGTCCAGGGGGTCGAGAAGGAATATATCTAAAATCACGTTCGCCAACTGCGGGTATACTAGGTCGCCGGGAAACCTTCTTATTTCGCGAAACCCGGGTTTAGAATCCAGCGATAAAGGACCGAACAATCTTCAGGTAGCACACGCAAGTAAGGGCACAGAAAAATGGTTCTTTTATAGTCAATAGTGAACTCGAATTTTAGAACAAGTACGAGTTA"

print(dna_reverse_complement(string))
